general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
# normal = { family = "JetBrains Mono" }
# bold = { family = "JetBrains Mono" }
# italic = { family = "JetBrains Mono" }
normal = {family = "JetBrains Mono" }
bold = {family = "JetBrains Mono" }
italic = {family = "JetBrains Mono" }
bold_italic = {family = "JetBrains Mono"}
size = 11

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.98

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

[terminal]
[terminal.shell]
program = "tmux"
