[window]
opacity = 1
decorations = "None"
[font]
# normal = {family = "JetBrainsMono Nerd Font Mono", style = "Light" }
# bold = {family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
# italic = {family = "JetBrainsMono Nerd Font Mono", style = "Light" }
# bold_italic = {family = "JetBrainsMono Nerd Font Mono", style = "Regular"}
normal = {family = "Iosevka Nerd Font Mono", style = "Regular" }
bold = {family = "Iosevka Nerd Font Mono", style = "Bold" }
italic = {family = "Iosevka Nerd Font Mono", style = "Light" }
bold_italic = {family = "Iosevka Nerd Font Mono", style = "Bold"}
size = 15.5
[mouse]
hide_when_typing = true

[terminal]
[terminal.shell]
program = "tmux"
